env: firefighters
scenario: "2-8a_2-8b_50"

env_args:
  entity_scheme: True
  episode_limit: 150
  reward_scale: 20

test_nepisode: 160
test_interval: 50000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 10000000
